<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>agj_museo-pytest.xml</title>
    <style type="text/css">
        body {
    background-color: white;
    padding-bottom: 20em;
    margin: 0;
    min-height: 15cm;
}

h1, h2, h3, h4, h5, h6, h7 {
    font-family: sans-serif;
}

h1 {
    background-color: #007acc;
    color: white;
    padding: 3mm;
    margin-top: 0;
    margin-bottom: 1mm;
}

.footer {
    font-style: italic;
    font-size: small;
    text-align: right;
    padding: 1em;
}

.testsuite {
    padding-bottom: 2em;
    margin-left: 1em;
}

.proplist {
    width: 100%;
    margin-bottom: 2em;
    border-collapse: collapse;
    border: 1px solid grey;
}

.proplist th {
    background-color: silver;
    width: 5em;
    padding: 2px;
    padding-right: 1em;
    text-align: left;
}

.proplist td {
    padding: 2px;
}

.index-table {
    width: 90%;
    margin-left: 1em;
}

.index-table td {
    vertical-align: top;
    max-width: 200px;
    word-wrap: break-word;
}

.failure-index {

}

.toc {
    margin-bottom: 2em;
    font-family: monospace;
}

.stdio, pre {
    min-height: 1em;
    background-color: #1e1e1e;
    color: silver;
    padding: 0.5em;
}
.tdpre {
    background-color: #1e1e1e;
}

.test {
    margin-left: 0.5cm;
}

.outcome {
    border-left: 1em;
    padding: 2px;
}

.outcome-failed {
    border-left: 1em solid lightcoral;
}

.outcome-passed {
    border-left: 1em solid lightgreen;
}

.outcome-skipped {
    border-left: 1em dotted silver;
}

.stats-table {
}

.stats-table td {
    min-width: 4em;
    text-align: right;
}

.stats-table .failed {
    background-color: lightcoral;
}

.stats-table .passed {
    background-color: lightgreen;
}

.matrix-table {
    table-layout: fixed;
    border-spacing: 0;
    width: available;
    margin-left: 1em;
}

.matrix-table td {
    vertical-align: center;
}

.matrix-table td:last-child {
    width: 0;
}

.matrix-table tr:hover {
    background-color: yellow;
}

.matrix-axis-name {
    white-space: nowrap;
    padding-right: 0.5em;
    border-left: 1px solid black;
    border-top: 1px solid black;
    text-align: right;
}

.matrix-axis-line {
    border-left: 1px solid black;
    width: 0.5em;
}

.matrix-classname {
    text-align: left;
    width: 100%;
    border-top: 2px solid grey;
    border-bottom: 1px solid silver;
}

.matrix-casename {
    text-align: left;
    font-weight: normal;
    font-style: italic;
    padding-left: 1em;
    border-bottom: 1px solid silver;
}

.matrix-result {
    display: block;
    width: 1em;
    text-align: center;
    padding: 1mm;
    margin: 0;
}

.matrix-result-combined {
    white-space: nowrap;
    padding-right: 0.2em;
    text-align: right;
}

.matrix-result-failed {
    background-color: lightcoral;
}

.matrix-result-passed {
    background-color: lightgreen;
}

.matrix-result-skipped {
    background-color: lightyellow;
}

.matrix-even {
    background-color: lightgray;
}
    </style>
</head>
<body>
    
<h1>
    Test Report : agj_museo-pytest.xml
</h1>
<a id="toc"></a>
<table class="index-table">
    <tr>
        <td>
            <ul class="toc">
            
                
                <li>test_minimal_requirements.TestRNF1
                <ul>
                    
                    <li><a href="#4d7b7350-a2e5-4571-8b26-a9f1bff619e1">test_app_tiene_al_menos_4_modelos</a></li>
                    
                    <li><a href="#cc1351c0-c6d7-4363-8643-edc01281b675">test_modelos_en_ficheros_individuales</a></li>
                    
                </ul>
                </li>
                
                <li>test_minimal_requirements.TestRNF2
                <ul>
                    
                    <li><a href="#f8f82b74-dff4-4c05-9e65-584ef80b5c4c">test_relacion_many2many</a></li>
                    
                    <li><a href="#640f056e-72e8-4812-9f0d-e3e21c96b114">test_modelos_tienen_algun_campo_relacion[one2many]</a></li>
                    
                    <li><a href="#924194b8-1764-43ed-a5bc-4e2c9b9e97ba">test_modelos_tienen_algun_campo_relacion[many2one]</a></li>
                    
                    <li><a href="#65194ca8-2ed2-4789-9b19-9c6662d65ef9">test_unknown_comodel_name</a></li>
                    
                </ul>
                </li>
                
                <li>test_minimal_requirements.TestRNF3
                <ul>
                    
                    <li><a href="#0c05d246-04d6-4995-a412-fb10d706597b">test_modelos_tienen_vista[tree]</a></li>
                    
                    <li><a href="#3c3b6900-6e79-4a13-a341-0d1e5d7aab95">test_modelos_tienen_vista[form]</a></li>
                    
                    <li><a href="#6d635cee-eec9-4610-8053-8a92d365833d">test_formularios_tienen_vista_anidada_para_campos_X2many[one2many]</a></li>
                    
                    <li><a href="#6c2d12d4-fc2b-44cb-91ad-87b6ef368cab">test_formularios_tienen_vista_anidada_para_campos_X2many[many2many]</a></li>
                    
                </ul>
                </li>
                
                <li>test_minimal_requirements.TestRNF4
                <ul>
                    
                    <li><a href="#faf1b546-0b3f-4849-afee-dbabfb951b0b">test_vistas_en_ficheros_individuales</a></li>
                    
                </ul>
                </li>
                
                <li>test_minimal_requirements.TestRNF5
                <ul>
                    
                    <li><a href="#23da5972-f298-48f0-aefd-164c87368c63">test_modelos_tienen_algun_posible_campo_imagen</a></li>
                    
                    <li><a href="#40f2fabe-86bb-4d7f-88ff-e6f37ba7e8c1">test_alguna_vista_tiene_campo_imagen</a></li>
                    
                </ul>
                </li>
                
                <li>test_minimal_requirements.TestRNF6
                <ul>
                    
                    <li><a href="#37a019b9-eae7-46d6-8f0e-c2699a1e52a7">test_modelos_tienen_acciones</a></li>
                    
                    <li><a href="#3b0a0145-59bb-47c0-8053-277b2fc5813f">test_hay_elementos_de_menu[.//menuitem[@action]]</a></li>
                    
                </ul>
                </li>
                
                <li>test_minimal_requirements.TestRNF7
                <ul>
                    
                    <li><a href="#e8842fa1-b922-4b58-a53a-93565a2d8574">test_modelos_tienen_permisos</a></li>
                    
                </ul>
                </li>
                
                <li>test_minimal_requirements.TestRNF8
                <ul>
                    
                    <li><a href="#0f6ac55f-a2b1-41a1-95d2-0286dcfdd9a2">test_app_tiene_icono</a></li>
                    
                </ul>
                </li>
                
            
            </ul>
        </td>
        <td class="failure-index">
            <ul class="toc">
            
                
                    
                    
                    <li><a href="#4d7b7350-a2e5-4571-8b26-a9f1bff619e1">[F] test_minimal_requirements.TestRNF1 : test_app_tiene_al_menos_4_modelos</a></li>
                    
                    
                    
                    <li><a href="#cc1351c0-c6d7-4363-8643-edc01281b675">[F] test_minimal_requirements.TestRNF1 : test_modelos_en_ficheros_individuales</a></li>
                    
                    
                
                    
                    
                    <li><a href="#f8f82b74-dff4-4c05-9e65-584ef80b5c4c">[F] test_minimal_requirements.TestRNF2 : test_relacion_many2many</a></li>
                    
                    
                    
                    <li><a href="#640f056e-72e8-4812-9f0d-e3e21c96b114">[F] test_minimal_requirements.TestRNF2 : test_modelos_tienen_algun_campo_relacion[one2many]</a></li>
                    
                    
                    
                    <li><a href="#924194b8-1764-43ed-a5bc-4e2c9b9e97ba">[F] test_minimal_requirements.TestRNF2 : test_modelos_tienen_algun_campo_relacion[many2one]</a></li>
                    
                    
                    
                    <li><a href="#65194ca8-2ed2-4789-9b19-9c6662d65ef9">[F] test_minimal_requirements.TestRNF2 : test_unknown_comodel_name</a></li>
                    
                    
                
                    
                    
                    <li><a href="#0c05d246-04d6-4995-a412-fb10d706597b">[F] test_minimal_requirements.TestRNF3 : test_modelos_tienen_vista[tree]</a></li>
                    
                    
                    
                    <li><a href="#3c3b6900-6e79-4a13-a341-0d1e5d7aab95">[F] test_minimal_requirements.TestRNF3 : test_modelos_tienen_vista[form]</a></li>
                    
                    
                    
                    <li><a href="#6d635cee-eec9-4610-8053-8a92d365833d">[F] test_minimal_requirements.TestRNF3 : test_formularios_tienen_vista_anidada_para_campos_X2many[one2many]</a></li>
                    
                    
                    
                    <li><a href="#6c2d12d4-fc2b-44cb-91ad-87b6ef368cab">[F] test_minimal_requirements.TestRNF3 : test_formularios_tienen_vista_anidada_para_campos_X2many[many2many]</a></li>
                    
                    
                
                    
                    
                    <li><a href="#faf1b546-0b3f-4849-afee-dbabfb951b0b">[F] test_minimal_requirements.TestRNF4 : test_vistas_en_ficheros_individuales</a></li>
                    
                    
                
                    
                    
                    <li><a href="#23da5972-f298-48f0-aefd-164c87368c63">[F] test_minimal_requirements.TestRNF5 : test_modelos_tienen_algun_posible_campo_imagen</a></li>
                    
                    
                    
                    <li><a href="#40f2fabe-86bb-4d7f-88ff-e6f37ba7e8c1">[F] test_minimal_requirements.TestRNF5 : test_alguna_vista_tiene_campo_imagen</a></li>
                    
                    
                
                    
                    
                    <li><a href="#37a019b9-eae7-46d6-8f0e-c2699a1e52a7">[F] test_minimal_requirements.TestRNF6 : test_modelos_tienen_acciones</a></li>
                    
                    
                    
                    <li><a href="#3b0a0145-59bb-47c0-8053-277b2fc5813f">[F] test_minimal_requirements.TestRNF6 : test_hay_elementos_de_menu[.//menuitem[@action]]</a></li>
                    
                    
                
                    
                    
                    <li><a href="#e8842fa1-b922-4b58-a53a-93565a2d8574">[F] test_minimal_requirements.TestRNF7 : test_modelos_tienen_permisos</a></li>
                    
                    
                
                    
                    
                    <li><a href="#0f6ac55f-a2b1-41a1-95d2-0286dcfdd9a2">[F] test_minimal_requirements.TestRNF8 : test_app_tiene_icono</a></li>
                    
                    
                
            
            </ul>
        </td>
    </tr>
</table>


    <div class="testsuite">
        <h2>Test Suite: pytest</h2>
        <a id="4de3fc56-e480-4a69-b170-941cbdb5673d"></a>
        
        
        <h3>Results</h3>
        <table class="proplist">
            <tr>
                <th>Duration</th><td>0.986 sec</td>
            </tr>
            <tr>
                <th>Tests</th><td>17</td>
            </tr>
            <tr>
                <th>Failures</th><td>17</td>
            </tr>
        </table>

        <div class="testclasses">
            <h3>Tests</h3>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF1</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="4d7b7350-a2e5-4571-8b26-a9f1bff619e1"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_app_tiene_al_menos_4_modelos</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.075 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="cc1351c0-c6d7-4363-8643-edc01281b675"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_en_ficheros_individuales</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF2</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="f8f82b74-dff4-4c05-9e65-584ef80b5c4c"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_relacion_many2many</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="640f056e-72e8-4812-9f0d-e3e21c96b114"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_tienen_algun_campo_relacion[one2many]</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="924194b8-1764-43ed-a5bc-4e2c9b9e97ba"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_tienen_algun_campo_relacion[many2one]</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="65194ca8-2ed2-4789-9b19-9c6662d65ef9"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_unknown_comodel_name</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF3</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="0c05d246-04d6-4995-a412-fb10d706597b"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_tienen_vista[tree]</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="3c3b6900-6e79-4a13-a341-0d1e5d7aab95"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_tienen_vista[form]</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="6d635cee-eec9-4610-8053-8a92d365833d"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_formularios_tienen_vista_anidada_para_campos_X2many[one2many]</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="6c2d12d4-fc2b-44cb-91ad-87b6ef368cab"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_formularios_tienen_vista_anidada_para_campos_X2many[many2many]</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF4</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="faf1b546-0b3f-4849-afee-dbabfb951b0b"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_vistas_en_ficheros_individuales</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF5</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="23da5972-f298-48f0-aefd-164c87368c63"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_tienen_algun_posible_campo_imagen</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="40f2fabe-86bb-4d7f-88ff-e6f37ba7e8c1"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_alguna_vista_tiene_campo_imagen</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF6</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="37a019b9-eae7-46d6-8f0e-c2699a1e52a7"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_tienen_acciones</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                    <div class="test outcome outcome-failed">
                        <a id="3b0a0145-59bb-47c0-8053-277b2fc5813f"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_hay_elementos_de_menu[.//menuitem[@action]]</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF7</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="e8842fa1-b922-4b58-a53a-93565a2d8574"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_modelos_tienen_permisos</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
            <div class="testclass">
                <h4>test_minimal_requirements.TestRNF8</h4>
                <div class="testcases">
                
                    <div class="test outcome outcome-failed">
                        <a id="0f6ac55f-a2b1-41a1-95d2-0286dcfdd9a2"></a>
                        <table class="proplist">
                            <tr><th>Test case:</th><td><b>test_app_tiene_icono</b></td></tr>
                            <tr><th>Outcome:</th><td>Failed</td></tr>
                            <tr><th>Duration:</th><td>0.001 sec</td></tr>
                        
                            <tr><th>Failed</th><td>failed on setup with &#34;Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
 Network pytest137292_default  Creating
 Network pytest137292_default  Error
failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
&#34;&#34;&#34;.&#34;</td></tr>
                        
                        
                        </table>

                        
                        <pre>docker_compose_command = &#39;docker compose&#39;, docker_compose_file = &#39;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#39;, docker_compose_project_name = &#39;pytest137292&#39;
docker_setup = [&#39;up --build -d&#39;], docker_cleanup = [&#39;down -v&#39;]

    @pytest.fixture(scope=containers_scope)
    def docker_services(
        docker_compose_command: str,
        docker_compose_file: Union[List[str], str],
        docker_compose_project_name: str,
        docker_setup: str,
        docker_cleanup: str,
    ) -&gt; Iterator[Services]:
        &#34;&#34;&#34;Start all services from a docker compose file (`docker-compose up`).
        After test are finished, shutdown all services (`docker-compose down`).&#34;&#34;&#34;
    
&gt;       with get_docker_services(
            docker_compose_command,
            docker_compose_file,
            docker_compose_project_name,
            docker_setup,
            docker_cleanup,
        ) as docker_service:

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:238: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.8/contextlib.py:113: in __enter__
    return next(self.gen)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:212: in get_docker_services
    docker_compose.execute(command)
.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:140: in execute
    return execute(command)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = &#39;docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d&#39;, success_codes = (0,)

    def execute(command: str, success_codes: Iterable[int] = (0,)) -&gt; Union[bytes, Any]:
        &#34;&#34;&#34;Run a shell command.&#34;&#34;&#34;
        try:
            output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
            status = 0
        except subprocess.CalledProcessError as error:
            output = error.output or b&#34;&#34;
            status = error.returncode
            command = error.cmd
    
        if status not in success_codes:
&gt;           raise Exception(
                &#39;Command {} returned {}: &#34;&#34;&#34;{}&#34;&#34;&#34;.&#39;.format(command, status, output.decode(&#34;utf-8&#34;))
            )
E           Exception: Command docker compose -f &#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml&#34; -p &#34;pytest137292&#34; up --build -d returned 1: &#34;&#34;&#34;time=&#34;2025-02-26T17:30:42+01:00&#34; level=warning msg=&#34;/home/madrid/Escritorio/SGE/SGE-odoo-project-tester/projects/docker-compose.yml: `version` is obsolete&#34;
E            Network pytest137292_default  Creating
E            Network pytest137292_default  Error
E           failed to create network pytest137292_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
E           &#34;&#34;&#34;.

.venv/lib/python3.8/site-packages/pytest_docker/plugin.py:35: Exception</pre>
                        
                        

                        
                        
                        
                    </div>
                
                </div>
            </div>
            
        </div>
    </div>
    



<p class="footer">
    Generated by junit2html
</p>
</body>
</html>